server:
  port: 8080

spring:
  rabbitmq:
    host: ${qiaopi.rabbitmq.host} # 你的虚拟机IP
    port: ${qiaopi.rabbitmq.port} # 端口
    virtual-host: ${qiaopi.rabbitmq.virtual-host} # 虚拟主机
    username: ${qiaopi.rabbitmq.username} # 用户名
    password: ${qiaopi.rabbitmq.password} # 密码
  servlet:
    multipart:
      max-file-size: 10MB # 单个上传文件的最大限制大小
      max-request-size: 20MB # 单次请求的最大限制大小
  # 模式切换
  profiles:
    active: dev
  main:
    allow-circular-references: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: -1 # 可以设置缓存时间，-1 表示不缓存
    fallback-to-system-locale: true
  datasource:
    # 数据源基本配置
    driver-class-name: ${qiaopi.datasource.driver-class-name}
    url: jdbc:mysql://${qiaopi.datasource.host}:${qiaopi.datasource.port}/${qiaopi.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${qiaopi.datasource.username}
    password: ${qiaopi.datasource.password}
    type: com.alibaba.druid.pool.DruidDataSource
  # 数据源其他配置
  druid:
    # 配置初始化大小、最小、最大线程数
    initialSize: 5
    minIdle: 5
    # CPU核数+1，也可以大些但不要超过20，数据库加锁时连接过多性能下降
    maxActive: 20
    # 最大等待时间，内网：800，外网：1200（三次握手1s）
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最大空间时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    # 设置从连接池获取连接时是否检查连接有效性，true检查，false不检查
    testOnBorrow: false
    # 设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
    testOnReturn: true
    # 可以支持PSCache（提升写入、查询效率）
    poolPreparedStatements: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 保持长连接
    keepAlive: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  data:
    redis:
      host: ${qiaopi.redis.host}
      password: ${qiaopi.redis.password}
      database: ${qiaopi.redis.database}
      port: ${qiaopi.redis.port}
  mail:
    host: ${qiaopi.mail.host}
    protocol: smtp
    default-encoding: UTF-8
    username: ${qiaopi.mail.username}
    password: ${qiaopi.mail.password}
    nickname: 侨缘信使
    properties:
      mail.smtp.auth: true # 启用SMTP服务器的身份验证，这是为了确保只有合法用户可以发送邮件。
      mail.smtp.starttls.enable: true # 启用TLS加密，这是为了确保邮件传输的安全性。
      mail.smtp.starttls.required: true # 要求使用TLS加密，如果连接不是通过TLS加密传输，则连接将失败。

mybatis-plus:
  global-config:
    db-config:
      id-type: auto # 全局id类型为自增长
    mapper-locations: "classpath*:/mapper/**/*.xml" # Mapper.xml文件地址，当前这个是默认值

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'qiaopi'
      paths-to-match: '/**'
      packages-to-scan: com.qiaopi.controller

# 文件上传配置
dromara:
  x-file-storage:  # 文件存储配置
    default-platform: minio-1 # 默认使用的存储平台
    thumbnail-suffix: ".min.png" # 缩略图后缀，例如【.min.jpg】【.png】
    minio:
      - platform: minio-1
        enable-storage: true  # 启用存储
        access-key: ${qiaopi.minio.access-key}
        secret-key: ${qiaopi.minio.secret-key}
        end-point: ${qiaopi.minio.end-point}
        bucket-name: ${qiaopi.minio.bucket-name}
        domain: ${qiaopi.minio.domain} # 访问域名，注意“/”结尾，例如：http://minio.abc.com/abc/
        base-path: ${qiaopi.minio.base-path} # 基础路径

# AES加密
aes:
  secret:
    key: ${qiaopi.aes.secret-key}

zhipu:
  api:
    key: ${qiaopi.zhipu.api-key}
