qiaopi:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 110.41.58.26
    port: 3306
    database: qiaopi
    username: Qiaopi
    password: 123456

  alioss:
    endpoint: https://oss-cn-guangzhou.aliyuncs.com
    accessKeyId: LTAI5tLNaiHCBNss9PtQnuRc
    accessKeySecret: KrOp7EyiY78PLSbxwaw8GKRGSLDWi2
    bucket-name: qiaopi

  redis:
    host: 110.41.58.26
    port: 6379
    password: 123456
    database: 1
