
#本地利用cpolar挂载公网ip

qiaopi:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: qiaopi
    username: root
    password: 1234

  alioss:
    endpoint: https://oss-cn-guangzhou.aliyuncs.com
    accessKeyId: LTAI5tLNaiHCBNss9PtQnuRc
    accessKeySecret: KrOp7EyiY78PLSbxwaw8GKRGSLDWi2
    bucket-name: qiaopi
  redis:
    host: localhost
    port: 6379
    password: 1234
    database: 1
