server:
  port: 8080

spring:
  profiles:
    active: prod
  main:
    allow-circular-references: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: -1 # 可以设置缓存时间，-1 表示不缓存
    fallback-to-system-locale: true
  datasource:
    #   数据源基本配置
    driver-class-name: ${qiaopi.datasource.driver-class-name}
    url: jdbc:mysql://${qiaopi.datasource.host}:${qiaopi.datasource.port}/${qiaopi.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${qiaopi.datasource.username}
    password: ${qiaopi.datasource.password}
    type: com.alibaba.druid.pool.DruidDataSource
  #   数据源其他配置
  druid:
    #     配置初始化大小、最小、最大线程数
    initialSize: 5
    minIdle: 5
    #     CPU核数+1，也可以大些但不要超过20，数据库加锁时连接过多性能下降
    maxActive: 20
    #     最大等待时间，内网：800，外网：1200（三次握手1s）
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    #     配置一个连接在池中最大空间时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    #     设置从连接池获取连接时是否检查连接有效性，true检查，false不检查
    testOnBorrow: true
    #     设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
    testOnReturn: true
    #     可以支持PSCache（提升写入、查询效率）
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    #     保持长连接
    keepAlive: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  data:
    redis:
      host: ${qiaopi.redis.host}
      password: ${qiaopi.redis.password}
      database: ${qiaopi.redis.database}
      port: ${qiaopi.redis.port}
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    username: 2794939382@qq.com
    password: icgqucgqohfcddca

    nickname: 侨批
    properties:
      mail.smtp.auth: true #启用SMTP服务器的身份验证，这是为了确保只有合法用户可以发送邮件。
      mail.smtp.starttls.enable: #启用TLS加密，这是为了确保邮件传输的安全性。
      mail.smtp.starttls.required: true #要求使用TLS加密，如果连接不是通过TLS加密传输，则连接将失败。


mybatis-plus:
  global-config:
    db-config:
      id-type: auto # 全局id类型为自增长
    mapper-locations: "classpath*:/mapper/**/*.xml" # Mapper.xml文件地址，当前这个是默认值
#mybatis:
#  #mapper配置文件
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.qiaopi.entity
#  configuration:
#    #开启驼峰命名
#    map-underscore-to-camel-case: true

logging:
  level:
    com:
      qiaopi:
        mapper: debug
        service: info
        controller: info

qiaopi:
  jwt:
#    一定要超过长度，否则会报错。确保secretKey至少有32个字符。
    user-secret-key: qiaopiqiaopiqiaopiqiaopiqiaopiqiaopiqiaopiqiaopiqiaopi
    user-ttl: 7200
    user-token-name: token
#    # 设置jwt签名加密时使用的秘钥
#    admin-secret-key: abc
#    # 设置jwt过期时间
#    admin-ttl: 7200000
#    # 设置前端传递过来的令牌名称
#    admin-token-name: token


  alioss:
    endpoint: ${qiaopi.alioss.endpoint}
    access-key-id: ${qiaopi.alioss.access-key-id}
    access-key-secret: ${qiaopi.alioss.access-key-secret}
    bucket-name: ${qiaopi.alioss.bucket-name}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'qiaopi'
      paths-to-match: '/**'
      packages-to-scan: com.qiaopi.controller
# knife4j项目访问访问地址:http://127.0.0.1:8080/doc.html#/home
knife4j:
  enable: true
  # 设置为true以启用Knife4j增强功能,这将再应用程序中启用Knife4j UI
  setting:
    # language: 设置Knife4j UI的语言,默认为zh_cn,可选值为zh_cn或en
    language: zh_cn
  #开启生产环境屏蔽
  production: false
  #是否启用登录认证
  basic:
    enable: false
    username: admin # 自己设置一个
    password: 123456 # 自己设置一个

